-d /home/loksart/Documents/project_github/fpga_projects/clocked_logic_flipflop/impl/gwsynthesis/clocked_logic_flipflop.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/loksart/Documents/project_github/fpga_projects/clocked_logic_flipflop/src/clocked_logic_flipflop.cst
-cfg /home/loksart/Documents/project_github/fpga_projects/clocked_logic_flipflop/impl/pnr/device.cfg
-sdc /home/loksart/Documents/project_github/fpga_projects/clocked_logic_flipflop/src/clock_logic_flipflop.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
