-d /home/loksart/Documents/fpga/fpga_project/and_gate/impl/gwsynthesis/and_gate.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/loksart/Documents/fpga/fpga_project/and_gate/src/and_gate.cst
-cfg /home/loksart/Documents/fpga/fpga_project/and_gate/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
